version: "3.7"
services:
  documentation:
    build:
      context: ./
    volumes:
      - .:/usr/src/app
    container_name: documentation
    image: apikom_documentations
    ports:
      - "8081:8081"
