openapi: 3.0.0

info:
  title: "APIKOM API"
  description: "API for APIKOM"
  version: "1.0.0"
servers:
  - url: http://localhost:8082/api/v1
paths: 
  /user-profile:
    post:
      description: "Create new user profile"
      tags:
        - "UserProfile"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfile'
      responses:
        201:
          description: "Created"
        401:
          description: "Access Denied"
        422:
          description: "Validation Error"
        500:
          description: "Server Error"
  /user-profile/me:
    get:
      description: "Get my user profile"
      security:
        - bearerAuth: []
      tags:
        - "UserProfile"
      responses:
        200:
          description: "OK"
        404:
          description: "Not Found"
        500:
          description: "Server Error"
  /user-profile/{profileId}:
    get:
      description: "Get user profile detail"
      parameters:
        - in: path
          required: true
          name: profileId
          schema:
            type: string
          description: Get user profile by id  
      tags:
        - "UserProfile"
      responses:
        200:
          description: "OK"
        404:
          description: "User profile not found"
        500:
          description: "Server Error"
    put:
      description: "update user profile by id"
      tags:
        - "UserProfile"
      parameters:
      - in: path
        required: true
        name: profileId
        schema:
          type: string
        description: update user profile detail by id  
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf: 
                - $ref: '#/components/schemas/UserProfile'
      responses:
        200:
          description: "OK"
        401:
          description: "Access Denied"
        404:
          description: "User profile not found"
        422:
          description: "Validation Error"
        500:
          description: "Server Error"
    delete:
      description: "Delete user profile by id"
      parameters:
      - in: path
        required: true
        name: profileId
        schema:
          type: string
        description: Get user profile detail by id  
      security:
        - bearerAuth: []
      tags:
        - "UserProfile"
      responses:
        200:
          description: "OK"
        404:
          description: "Product not found"
        500:
          description: "Server Error"
components:
  schemas:
    UserProfile:
      type: object
      properties:
        firstName:
          type: string
          example: "Yoshi"
        lastName:
          type: string
          example: "Nakamura"
        address:
          type: string
          example: "Mataram"
        about:
          type: string
          example: "Manusia bernapas"
        job:
          type: string
          example: "QA Tester"
        birthday:
          type: string
          example: "23:05:2020"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  

    

  