version: '3.7'
services:
  authentication:
    build: './authentication'
    ports:
      - "8082:8082"
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - authentication