version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DEV}
      POSTGRES_USER: ${POSTGRES_USERNAME_DEV}
      POSTGRES_DB: ${POSTGRES_DATABASE_DEV}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: ./
    volumes:
      - .:/usr/src/app
    image: products
    links:
      - db
    depends_on:
      - db
    ports:
      - "8083:8083"
