openapi: 3.0.0

info:
  title: "Ecommerce APP API"
  description: "API for ecommerce app"
  version: "1.0.0"
servers:
  - url: http://localhost:8000/api/v1
paths: 
  /categories:
    post:
      description: "Create new categories (ONLY ADMIN)"
      tags:
        - "Categories"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf: 
                - $ref: '#/components/schemas/Category'
      responses:
        201:
          description: "Created"
        401:
          description: "Access Denied"
        422:
          description: "Validation Error"
        500:
          description: "Server Error"
    get:
      description: "Get all categories (ONLY ADMIN)"
      tags:
        - "Categories"
      security:
        - bearerAuth: []
      responses:
        200:
          description: "Success"
        401:
          description: "Access Denied"
        500:
          description: "Server Error"
  /categories/{categoryId}:
    put:
      description: "update category by id (ONLY ADMIN)"
      tags:
        - "Categories"
      parameters:
      - in: path
        required: true
        name: categoryId
        schema:
          type: string
        description: update category by id  
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf: 
                - $ref: '#/components/schemas/Category'
      responses:
        200:
          description: "OK"
        401:
          description: "Access Denied"
        404:
          description: "Category not found"
        422:
          description: "Validation Error"
        500:
          description: "Server Error"
    delete:
      description: "Delete category by id (ONLY ADMIN)"
      parameters:
      - in: path
        required: true
        name: categoryId
        schema:
          type: string
        description: Get category by id  
      security:
        - bearerAuth: []
      tags:
        - "Categories"
      responses:
        200:
          description: "OK"
        404:
          description: "Category not found"
        500:
          description: "Server Error"
components:
  schemas:
    Category:
      type: object
      properties:
        name:
          type: string
          example: "electronics"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  

    

  