openapi: 3.0.0

info:
  title: "APIKOM API"
  description: "API for APIKOM"
  version: "1.0.0"
servers:
  - url: http://localhost:8081/api/v1
paths:
  /auth/google-login:
    post:
      description: "Login with facebook"
      tags:
        - "Authentication"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Token'
      responses:
        '200':
          description: "User successfully login"


  /auth/firebase-register:
    post:
      description: "Register with email"
      tags:
        - "Authentication"
      requestBody:
        # required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserWithEmail'
      responses:
        '201':
          description: User successfully registered
        '422':
          description: Validation error
        '500':
          description: Server Error
  /auth/firebase-login:
    post:
      description: "Login with Email"
      tags:
        - "Authentication"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "antoni@gmail.com"
                password:
                  type: string
                  example: "Testing12,."
      responses:
        '200':
          description: Login successfully
  /auth/username-register:
    post:
      description: "Register with email"
      tags:
        - "Authentication"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserWithUsername'
      responses:
        '201':
          description: User successfully registered
        '422':
          description: Validation error
        '500':
          description: Server Error
  /auth/username-login:
    post:
      description: "Login with Username"
      tags:
        - "Authentication"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "antoni"
                password:
                  type: string
                  example: "Testing12,."
      responses:
        '200':
          description: User successfully login

  /auth/facebook-login:
    post:
      description: "Login with facebook"
      tags:
        - "Authentication"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Token'
      responses:
        '200':
          description: User successfully login
  /auth/refresh-token:
    post:
      description: "Revoke Refresh Token"
      tags:
        - "Authentication"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                uid:
                  type: string
                  example: "aduwudhuwhduw"
      responses:
        '200':
          description: Refresh token revoked successfully
  /auth/logout:
    post:
      tags:
        - Authentication
      summary: Logout
      responses:
        '200':
          description: Signout successfully
  /auth/check-auth:
    post:
      tags:
        - Authentication
      summary: Check Authentication
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User authenticated
components:
  schemas:
    UserWithUsername:
      type: object
      properties:
        displayName:
          type: string
          description: only contain alphapet or space
          pattern: '/^[a-zA-Z ]*$/'
          example: 'antoni'
        username:
          type: string
          example: "antoni"
        phoneNumber:
          type: string
          example: "+6286532123215"
        password:
          type: string
          minimum: 8
          description: password must be at least one uppercase letter, one lowercase letter,
            one number and one special character
          example: "Testing12,."
        passwordConfirmation:
          type: string
          example: "Testing12,."
    UserWithEmail:
      type: object
      properties:
        displayName:
          type: string
          description: only contain alphapet or space
          pattern: '/^[a-zA-Z ]*$/'
          example: 'antoni'
        email:
          type: string
          example: "antoni@gmail.com"
        phoneNumber:
          type: string
          example: "+6286532126215"
        password:
          type: string
          minimum: 8
          description: >-
            password must be at least one uppercase letter, one lowercase letter,
            one number and one special character
          example: "Testing12,."
        passwordConfirmation:
          type: string
          example: "Testing12,."
    Token:
      type: object
      properties:
        token:
          type: string
          example: "aduwudhuwhduw"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT